### ISSUE TITLE
move "Honors for our award-winning website!" to a post

### ISSUE THREAD

**Issue by rskoenig** [Digital-nest/website-issue-log#10]
This seems cheesy to me - the nicest sites generally don't need to advertise that they have received awards on the site itself - maybe on the product/service that the site is advertising.

**Comment by kirstiscott** [comment]
Can you ask Linda Bixby if it's ok to create a blog post for this and remove it from the footer?

**Comment by kirstiscott** [comment]
Linda said this is OK to do so I will take care of it when the site is back up.
