### ISSUE TITLE
Make an events post category and attach the feed to the schedule page

### ISSUE THREAD

**Issue by Yazmini** [Digital-nest/website-issue-log#13]
I want to keep using Google Calendar as the visual calendar. I just want a feed for the events below with a description, sign up button and thumbnail the way it is now. The problem with how it is now is that it is built as is the page is static and the content on it is not.

**Comment by kirstiscott** [comment]
Good idea. We'll add a new category. It would be great to have an archive of past events so they are still searchable, plus they would be easy to duplicate in the future. I'll have Bill work on a plan.
